In [383]:
import numpy as np#load ice cube data
from scipy.optimize import minimize
import pandas as pd
import matplotlib.pyplot as plt
from scipy.integrate import quad


In [384]:
files=["IC40_exp_new.csv","IC59_exp_new.csv","IC79_exp_new.csv","IC86_I_exp_new.csv","IC86_II_exp_new.csv", 
       "IC86_III_exp_new.csv","IC86_IV_exp_new.csv","IC86_V_exp_new.csv","IC86_VI_exp_new.csv",
       "IC86_VII_exp_new.csv"]

In [385]:
data=np.loadtxt("IC40_exp_new.csv")
for name in files[1:]:#indexing the list
    da=np.loadtxt(name)
    data=np.vstack((data,da))#load everyfile
mjd,log10_E,Ang_err,RA,Dec,Azim,Zenith=data.T
len(RA)
    

1134431

In [386]:
fields=[log10_E,RA,Dec,Ang_err]
print(Dec)
iceang=fields[3]

[ 16.76  -13.371  11.29  ...  42.543  44.72    4.708]


In [387]:
print(fields)

[array([3.31, 5.17, 3.92, ..., 2.88, 2.98, 3.28]), array([203.024,  75.024,  97.501, ..., 308.127, 332.199, 213.309]), array([ 16.76 , -13.371,  11.29 , ...,  42.543,  44.72 ,   4.708]), array([0.48, 0.62, 0.56, ..., 0.3 , 0.21, 0.25])]


In [388]:
df=pd.read_csv("TabO1.csv")
#print(df)
df.loc[31, 'RA'] = '08 43 00.0'
df.loc[31, 'Decl'] = '+73 30 00'
df.loc[32, 'RA'] = '00 47 30.0'
df.loc[32, 'Decl'] = '-25 11 37 '
df.loc[33,'RA']='09 52 34.1'
df.loc[33,'Decl']='+68 50 42'
df.loc[34,'RA']='00 44 18.0'
df.loc[34,'Decl']='+42 18 00'
df.loc[35,'RA']='13 42 06.24'
df.loc[35,'Decl']='-26 53 48.1'
df.loc[36,'RA']='00 49 12.0 '
df.loc[36,'Decl']='26 06 00  '

df.to_csv("updated_file.csv", index=False)
print(df)

#df.loc[1, 'RA'] = '09 55 59.28'
#df.loc[1, 'Decl'] = '+69 41 02.40'


                     Name     Period    Period_Err Pdot_lim          Pdot  \
0   CXOU J010043.1-721134   8.020392  9.000000e-06      NaN  1.880000e-11   
1              4U 0142+61   8.688692  5.000000e-08      NaN  2.022000e-12   
2           SGR 0418+5729   9.078388  5.000000e-08      NaN  4.000000e-15   
3           SGR 0501+4516   5.762069  1.000000e-07      NaN  5.940000e-12   
4             SGR 0526-66   8.054400  2.000000e-04      NaN  3.800000e-11   
5          1E 1048.1-5937   6.457875  3.000000e-06      NaN  2.250000e-11   
6          1E 1547.0-5408   2.072125  1.000000e-07      NaN  4.770000e-11   
7          PSR J1622-4950   4.326100  1.000000e-04      NaN  1.700000e-11   
8             SGR 1627-41   2.594578  6.000000e-06      NaN  1.900000e-11   
9   CXOU J164710.2-455216  10.610644  1.700000e-05        <  4.000000e-13   
10  1RXS J170849.0-400910  11.005025  1.700000e-07      NaN  1.945500e-11   
11  CXOU J171405.7-381031   3.825352  4.000000e-06      NaN  6.400000e-11   

In [389]:
df1=df.rename({'RA':'RA_M'},axis=1)
print(df1)

                     Name     Period    Period_Err Pdot_lim          Pdot  \
0   CXOU J010043.1-721134   8.020392  9.000000e-06      NaN  1.880000e-11   
1              4U 0142+61   8.688692  5.000000e-08      NaN  2.022000e-12   
2           SGR 0418+5729   9.078388  5.000000e-08      NaN  4.000000e-15   
3           SGR 0501+4516   5.762069  1.000000e-07      NaN  5.940000e-12   
4             SGR 0526-66   8.054400  2.000000e-04      NaN  3.800000e-11   
5          1E 1048.1-5937   6.457875  3.000000e-06      NaN  2.250000e-11   
6          1E 1547.0-5408   2.072125  1.000000e-07      NaN  4.770000e-11   
7          PSR J1622-4950   4.326100  1.000000e-04      NaN  1.700000e-11   
8             SGR 1627-41   2.594578  6.000000e-06      NaN  1.900000e-11   
9   CXOU J164710.2-455216  10.610644  1.700000e-05        <  4.000000e-13   
10  1RXS J170849.0-400910  11.005025  1.700000e-07      NaN  1.945500e-11   
11  CXOU J171405.7-381031   3.825352  4.000000e-06      NaN  6.400000e-11   

In [390]:
import re
def convert_ra_to_comma(ra):#replacing space with comma
    return re.sub(r"\s+", ",",ra.strip())
df1['RA_M_comma'] = df1['RA_M'].apply(convert_ra_to_comma)# Apply the function to the entire RA_M column
def convert_dec_to_comma(dec):
    return re.sub(r"\s+", ",",dec.strip())
df1['dec_M_comma'] = df1['Decl'].apply(convert_dec_to_comma)
    
print(df1[['Name', 'RA_M', 'RA_M_comma', 'Decl','dec_M_comma']])# Show the DataFrame with the new RA_M_Comma column

                     Name            RA_M      RA_M_comma            Decl  \
0   CXOU J010043.1-721134     01 00 43.14     01,00,43.14     -72 11 33.8   
1              4U 0142+61    01 46 22.407    01,46,22.407    +61 45 03.19   
2           SGR 0418+5729    04 18 33.867    04,18,33.867    +57 32 22.91   
3           SGR 0501+4516     05 01 06.76     05,01,06.76    +45 16 33.92   
4             SGR 0526-66     05 26 00.89     05,26,00.89     -66 04 36.3   
5          1E 1048.1-5937     10 50 07.14     10,50,07.14     -59 53 21.4   
6          1E 1547.0-5408  15 50 54.12386  15,50,54.12386  -54 18 24.1141   
7          PSR J1622-4950     16 22 44.89     16,22,44.89     -49 50 52.7   
8             SGR 1627-41    16 35 51.844    16,35,51.844    -47 35 23.31   
9   CXOU J164710.2-455216     16 47 10.20     16,47,10.20    -45 52 16.90   
10  1RXS J170849.0-400910     17 08 46.87     17,08,46.87    -40 08 52.44   
11  CXOU J171405.7-381031     17 14 05.74     17,14,05.74     -38 10 30.9   

In [391]:
def ra_to_degrees(ra_string):
    ra_parts = ra_string.split(',')
    ra_hours = int(ra_parts[0])  # Convert to integer (handles leading zeros)
    ra_minutes = int(ra_parts[1])  # Convert to integer (handles leading zeros)
    ra_seconds = float(ra_parts[2])  # Convert to float
    return (ra_hours * 15) + (ra_minutes / 4) + (ra_seconds / 240)
#field3.loc[:,'RA_M(deg)']=field3['RA_M_comma'].apply(ra_to_degrees)
def dec_to_degrees(dec_string):
    dec_parts = dec_string.split(',')
    dec_degrees = int(dec_parts[0])  # Convert to integer (handles leading zeros)
    dec_minutes = int(dec_parts[1])  # Convert to integer (handles leading zeros)
    dec_seconds = float(dec_parts[2])
    sign = 1 if dec_degrees >= 0 else -1
    return abs(dec_degrees) + (dec_minutes / 60) + (dec_seconds / 3600) * sign
df1['RA_M(deg)'] = df1['RA_M_comma'].apply(ra_to_degrees)
df1['Decl_M(deg)'] = df1['dec_M_comma'].apply(dec_to_degrees)
print(df1)

                     Name     Period    Period_Err Pdot_lim          Pdot  \
0   CXOU J010043.1-721134   8.020392  9.000000e-06      NaN  1.880000e-11   
1              4U 0142+61   8.688692  5.000000e-08      NaN  2.022000e-12   
2           SGR 0418+5729   9.078388  5.000000e-08      NaN  4.000000e-15   
3           SGR 0501+4516   5.762069  1.000000e-07      NaN  5.940000e-12   
4             SGR 0526-66   8.054400  2.000000e-04      NaN  3.800000e-11   
5          1E 1048.1-5937   6.457875  3.000000e-06      NaN  2.250000e-11   
6          1E 1547.0-5408   2.072125  1.000000e-07      NaN  4.770000e-11   
7          PSR J1622-4950   4.326100  1.000000e-04      NaN  1.700000e-11   
8             SGR 1627-41   2.594578  6.000000e-06      NaN  1.900000e-11   
9   CXOU J164710.2-455216  10.610644  1.700000e-05        <  4.000000e-13   
10  1RXS J170849.0-400910  11.005025  1.700000e-07      NaN  1.945500e-11   
11  CXOU J171405.7-381031   3.825352  4.000000e-06      NaN  6.400000e-11   

In [392]:
df1.at[32, 'Decl_M(deg)'] =- 25.02
df1.at[15, 'Decl_M(deg)'] = 16.11
df1.at[35, 'Decl_M(deg)'] =- 26.87 
df1.at[36, 'Decl_M(deg)'] = -26.10
field3 = df1[['RA_M(deg)', 'Decl_M(deg)']]
print(field3)


     RA_M(deg)  Decl_M(deg)
0    15.179750    72.173944
1    26.593363    61.750886
2    64.641113    57.539697
3    75.278167    45.276089
4    81.503708    66.056583
5   162.529750    59.877389
6   237.725516    54.293302
7   245.687042    49.818694
8   248.966017    47.576858
9   251.792500    45.861972
10  257.195292    40.118767
11  258.523917    38.158083
12  266.417350    28.991717
13  272.163904    20.388931
14  272.462862    19.702241
15  274.515417    16.110000
16  275.575000    16.059222
17  278.434875     8.514583
18  278.717158     8.734439
19  280.330596     4.930233
20  283.194458     0.554944
21  286.809708     9.322250
22  293.731657    21.896607
23  345.284562    58.879014
24  118.927000    29.536333
25  270.245833    22.920000
26  272.046667    20.619722
27  274.714083    15.977050
28  281.227833     2.918583
29  303.487083    34.330000
30  281.603917     2.958306
31  130.750000    73.500000
32   11.875000   -25.020000
33  148.142083    68.845000
34   11.075000    42

In [393]:
ra_mag=np.array(field3['RA_M(deg)'])
dec_mag=np.array(field3['Decl_M(deg)'])
ice_ra=(fields[1])
ice_dec=(fields[2])
print(ice_ra)
print(ice_dec)
print(ra_mag)
#print(dec_mag)|
print(dec_mag)

[203.024  75.024  97.501 ... 308.127 332.199 213.309]
[ 16.76  -13.371  11.29  ...  42.543  44.72    4.708]
[ 15.17975     26.5933625   64.6411125   75.27816667  81.50370833
 162.52975    237.72551608 245.68704167 248.96601667 251.7925
 257.19529167 258.52391667 266.41735    272.16390417 272.46286233
 274.51541667 275.575      278.434875   278.71715833 280.33059583
 283.19445833 286.80970833 293.7316575  345.2845625  118.927
 270.24583333 272.04666667 274.71408333 281.22783333 303.48708333
 281.60391667 130.75        11.875      148.14208333  11.075
 205.526       12.3       ]
[ 72.17394444  61.75088611  57.53969722  45.27608889  66.05658333
  59.87738889  54.29330164  49.81869444  47.57685833  45.86197222
  40.11876667  38.15808333  28.99171722  20.38893056  19.70224125
  16.11        16.05922222   8.51458333   8.73443889   4.93023333
   0.55494444   9.32225     21.89660733  58.87901389  29.53633333
  22.92        20.61972222  15.97705      2.91858333  34.33
   2.95830556  73.5       

In [394]:
column_namesarea = ["log10(E_nu/GeV)_min", "log10(E_nu/GeV)_max", "Dec_nu_min[deg]", "Dec_nu_max[deg]", "A_Eff[cm^2]"]
dataarea1= pd.read_csv("IC40_effectiveArea.csv", sep="\s+",  names=column_namesarea, skiprows=1)
dataarea2= pd.read_csv("IC59_effectiveArea.csv", sep="\s+", names=column_namesarea, skiprows=1)
dataarea3= pd.read_csv("IC79_effectiveArea.csv", sep="\s+", names=column_namesarea, skiprows=1)
dataarea4= pd.read_csv("IC86_I_effectiveArea.csv", sep="\s+",  names=column_namesarea, skiprows=1)
dataarea5= pd.read_csv("IC86_II_effectiveArea.csv", sep="\s+",  names=column_namesarea, skiprows=1)

In [395]:
gamma=-2.53
Emin1=dataarea1["log10(E_nu/GeV)_min"]
Emax1=dataarea1["log10(E_nu/GeV)_max"]
decmin1=dataarea1["Dec_nu_min[deg]"]
decmax1=dataarea1["Dec_nu_max[deg]"]
dec1=0.5*(decmin1+decmax1)
effarea1=dataarea1[ "A_Eff[cm^2]"]
Eff_1=[]
phiE_1=[]
for j in range(0,37):
    mdec=dec_mag[j]
    idx1=np.where((decmin1<=mdec)&(decmax1>mdec))
    log10E1=[0.5*(Emin1[i]+Emax1[i]) for i in idx1]
    A1=[effarea1[i] for i in idx1] #A in cm^2
    E1=pow(10,np.array(log10E1)-5)
    phiE1=E1**-gamma
    y1=A1*phiE1
    eff1=np.trapz(y1,x=E1)
    Eff_1.append(eff1)
    #phiE_1.append(phiE1)
#print(phiE_1)

In [396]:
#print(Eff_1)
#(phiE_1)

In [397]:
gamma=-2.53
Emin2=dataarea2["log10(E_nu/GeV)_min"]
Emax2=dataarea2["log10(E_nu/GeV)_max"]
decmin2=dataarea2["Dec_nu_min[deg]"]
decmax2=dataarea2["Dec_nu_max[deg]"]
dec2=0.5*(decmin2+decmax2)
effarea2=dataarea2[ "A_Eff[cm^2]"]
Eff_2=[]

for i in range(0,37):
    mdec=dec_mag[i]
    idx2=np.where((decmin2<=mdec)&(decmax2>mdec))
    log10E2=[0.5*(Emin2[i]+Emax2[i]) for i in idx2]
    A2=[effarea2[i] for i in idx2] #A in cm^2
    E2=pow(10,np.array(log10E2)-5)
    phiE2=E2**-gamma
    y2=A2*phiE2
    eff2=np.trapz(y2,x=E2)
    Eff_2.append(eff2)
print(Eff_2)
print(phiE2)

[array([4.97942152e+14]), array([8.64873574e+12]), array([7.77372024e+15]), array([5.65136948e+16]), array([8.64873574e+12]), array([7.77372024e+15]), array([4.20868873e+14]), array([5.2778216e+14]), array([3.08283203e+15]), array([5.65136948e+16]), array([2.03143342e+16]), array([2.90843304e+16]), array([6.49705961e+16]), array([3.05313913e+18]), array([3.05313913e+18]), array([1.40636314e+19]), array([1.40636314e+19]), array([1.75905395e+20]), array([1.75905395e+20]), array([5.34808417e+20]), array([4.60149792e+21]), array([7.272996e+19]), array([2.44168686e+18]), array([7.77372024e+15]), array([6.49705961e+16]), array([2.44168686e+18]), array([3.05313913e+18]), array([1.40636314e+19]), array([1.76546602e+21]), array([8.82345683e+17]), array([1.76546602e+21]), array([4.97942152e+14]), array([9.37526715e+20]), array([4.97942152e+14]), array([2.03143342e+16]), array([8.43190098e+20]), array([9.37526715e+20])]
[[4.60256574e-08 1.47570653e-07 4.73151259e-07 1.51705037e-06
  4.86407206e-0

In [398]:
gamma=-2.53
Emin3=dataarea3["log10(E_nu/GeV)_min"]
Emax3=dataarea3["log10(E_nu/GeV)_max"]
decmin3=dataarea3["Dec_nu_min[deg]"]
decmax3=dataarea3["Dec_nu_max[deg]"]
dec3=0.5*(decmin3+decmax3)
effarea3=dataarea3[ "A_Eff[cm^2]"]
Eff_3=[]

for i in range(0,37):
    mdec=dec_mag[i]
    idx3=np.where((decmin3<=mdec)&(decmax3>mdec))
    log10E3=[0.5*(Emin3[i]+Emax3[i]) for i in idx3]
    A3=[effarea3[i] for i in idx3] #A in cm^2
    E3=pow(10,np.array(log10E3)-5)
    phiE3=E3**-gamma
    y3=A3*phiE3
    eff3=np.trapz(y3,x=E3)
    Eff_3.append(eff3)
    
print(Eff_3)


[array([2.23290918e+14]), array([3.40098436e+15]), array([4.42614413e+14]), array([1.46402303e+15]), array([3.40098436e+15]), array([4.42614413e+14]), array([1.16837083e+17]), array([1.54013383e+17]), array([1.10599748e+16]), array([1.46402303e+15]), array([2.02515584e+17]), array([2.87018754e+15]), array([1.20232335e+17]), array([2.88707235e+18]), array([2.88707235e+18]), array([1.13566757e+19]), array([1.13566757e+19]), array([1.22421071e+20]), array([1.22421071e+20]), array([4.80597606e+20]), array([4.49468793e+21]), array([5.06691393e+19]), array([4.72939383e+17]), array([4.42614413e+14]), array([1.20232335e+17]), array([4.72939383e+17]), array([2.88707235e+18]), array([1.13566757e+19]), array([1.58892927e+21]), array([1.16034872e+17]), array([1.58892927e+21]), array([2.23290918e+14]), array([1.07699816e+21]), array([2.23290918e+14]), array([2.02515584e+17]), array([9.81763309e+20]), array([1.07699816e+21])]


In [399]:
gamma=-2.53
Emin=dataarea4["log10(E_nu/GeV)_min"]
Emax=dataarea4["log10(E_nu/GeV)_max"]
decmin=dataarea4["Dec_nu_min[deg]"]
decmax=dataarea4["Dec_nu_max[deg]"]
dec=0.5*(decmin+decmax)
effarea=dataarea4[ "A_Eff[cm^2]"]
Eff_4=[]
for i in range(0,37):
    mdec=dec_mag[i]
    idx=np.where((decmin<=mdec)&(decmax>mdec))
    log10E=[0.5*(Emin[i]+Emax[i]) for i in idx]
    A=[effarea[i] for i in idx] #A in cm^2
    E=pow(10,np.array(log10E)-5)
    phiE=E**-gamma
    y=A*phiE
    eff4=np.trapz(y,x=E)
    Eff_4.append(eff4)
#print (Eff_4)
print(idx)

(array([560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572,
       573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585,
       586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598,
       599], dtype=int64),)


In [400]:
gamma=-2.53
Emin=dataarea5["log10(E_nu/GeV)_min"]
Emax=dataarea5["log10(E_nu/GeV)_max"]
decmin=dataarea5["Dec_nu_min[deg]"]
decmax=dataarea5["Dec_nu_max[deg]"]
dec=0.5*(decmin+decmax)
effarea=dataarea5[ "A_Eff[cm^2]"]
Eff_5=[]
for i in range(0,37):
    mdec=dec_mag[i]
    idx=np.where((decmin<=mdec)&(decmax>mdec))
    log10E=[0.5*(Emin[i]+Emax[i]) for i in idx]
    A=[effarea[i] for i in idx] #A in cm^2
    E=pow(10,np.array(log10E)-5)
    phiE=E**-gamma
    y=A*phiE
    eff5=np.trapz(y,x=E)
    Eff_5.append(eff5)
   # print(idx)
print (Eff_5)


[array([2.89341641e+15]), array([3.76632962e+15]), array([5.68251941e+15]), array([9.21922006e+16]), array([3.76632962e+15]), array([5.68251941e+15]), array([3.10079663e+17]), array([1.78907589e+16]), array([2.10412946e+16]), array([9.21922006e+16]), array([1.10029083e+17]), array([6.27518902e+16]), array([1.56584634e+17]), array([2.14957957e+18]), array([2.14957957e+18]), array([9.33166567e+18]), array([9.33166567e+18]), array([2.42543007e+20]), array([2.42543007e+20]), array([7.14847312e+20]), array([4.27280148e+21]), array([9.36718813e+19]), array([3.64718166e+18]), array([5.68251941e+15]), array([1.56584634e+17]), array([3.64718166e+18]), array([2.14957957e+18]), array([9.33166567e+18]), array([1.78706371e+21]), array([2.50040149e+17]), array([1.78706371e+21]), array([2.89341641e+15]), array([1.53605117e+21]), array([2.89341641e+15]), array([1.10029083e+17]), array([1.44658337e+21]), array([1.53605117e+21])]


In [401]:
np.vstack([Eff_1,Eff_2,Eff_3,Eff_4,Eff_5])

array([[1.38800058e+13],
       [4.40854733e+13],
       [4.44958055e+11],
       [3.52008264e+16],
       [4.40854733e+13],
       [4.44958055e+11],
       [1.06744245e+13],
       [3.39076804e+15],
       [1.89337521e+14],
       [3.52008264e+16],
       [3.47584187e+14],
       [2.98121627e+14],
       [2.09232384e+18],
       [2.31704897e+18],
       [2.31704897e+18],
       [1.30124819e+21],
       [1.30124819e+21],
       [2.81370870e+22],
       [2.81370870e+22],
       [2.44271185e+23],
       [8.71255774e+24],
       [7.26952522e+21],
       [1.49301964e+20],
       [4.44958055e+11],
       [2.09232384e+18],
       [1.49301964e+20],
       [2.31704897e+18],
       [1.30124819e+21],
       [1.59210364e+24],
       [3.85026727e+16],
       [1.59210364e+24],
       [1.38800058e+13],
       [1.66823911e+23],
       [1.38800058e+13],
       [3.47584187e+14],
       [1.21251584e+23],
       [1.66823911e+23],
       [4.97942152e+14],
       [8.64873574e+12],
       [7.77372024e+15],


In [402]:
column_namestime=["MJD_start[days]","MJD_stop[days]"]
datatime1= pd.read_csv("IC40_exp(1).csv", sep="\s+",  names=column_namestime, skiprows=1)
datatime2= pd.read_csv("IC59_exp.csv", sep="\s+", names=column_namestime, skiprows=1)
datatime3= pd.read_csv("IC79_exp.csv", sep="\s+",  names=column_namestime, skiprows=1)
datatime4= pd.read_csv("IC86_I_exp.csv", sep="\s+",  names=column_namestime, skiprows=1)
datatime5= pd.read_csv("IC86_II_exp.csv", sep="\s+",  names=column_namestime, skiprows=1)
datatime6= pd.read_csv("IC86_III_exp.csv", sep="\s+",  names=column_namestime, skiprows=1)
datatime7= pd.read_csv("IC86_IV_exp.csv", sep="\s+",  names=column_namestime, skiprows=1)
datatime8= pd.read_csv("IC86_V_exp.csv", sep="\s+", names=column_namestime, skiprows=1)
datatime9= pd.read_csv("IC86_VI_exp.csv", sep="\s+",  names=column_namestime, skiprows=1)
datatime10= pd.read_csv("IC86_VII_exp.csv", sep="\s+",  names=column_namestime, skiprows=1)

In [403]:
#print(datatime10)
datatimesum1=np.sum(datatime1['MJD_stop[days]']-datatime1['MJD_start[days]'])
datatimesum2=np.sum(datatime2['MJD_stop[days]']-datatime2['MJD_start[days]'])
datatimesum3=np.sum(datatime3['MJD_stop[days]']-datatime3['MJD_start[days]'])
datatimesum4=np.sum(datatime4['MJD_stop[days]']-datatime4['MJD_start[days]'])
datatimesum5=np.sum(datatime5['MJD_stop[days]']-datatime5['MJD_start[days]'])
datatimesum6=np.sum(datatime6['MJD_stop[days]']-datatime6['MJD_start[days]'])
datatimesum7=np.sum(datatime7['MJD_stop[days]']-datatime7['MJD_start[days]'])
datatimesum8=np.sum(datatime8['MJD_stop[days]']-datatime8['MJD_start[days]'])
datatimesum9=np.sum(datatime9['MJD_stop[days]']-datatime9['MJD_start[days]'])
datatimesum10=np.sum(datatime10['MJD_stop[days]']-datatime10['MJD_start[days]'])
#print(datatimesum1)
print(datatimesum1)

376.3603109101532


In [404]:
expo_1=np.array(Eff_1)*datatimesum1
expo_2=np.array(Eff_2)*datatimesum2
expo_3=np.array(Eff_3)*datatimesum3
expo_4=np.array(Eff_4)*datatimesum4
expo_5=np.array(Eff_5)*datatimesum5
expo_6=np.array(Eff_5)*datatimesum6
expo_7=np.array(Eff_5)*datatimesum7
expo_8=np.array(Eff_5)*datatimesum8
expo_9=np.array(Eff_5)*datatimesum9
expo_10=np.array(Eff_5)*datatimesum10

In [405]:
total_exp=expo_1+expo_2+expo_3+expo_4+expo_5+expo_6+expo_7+expo_8+expo_9+expo_10
print(total_exp)
#len(total_exp)

[[7.97701715e+18]
 [9.62478651e+18]
 [2.86008692e+19]
 [2.36629301e+20]
 [9.62478651e+18]
 [2.86008692e+19]
 [7.18981769e+20]
 [9.25130054e+19]
 [5.52104279e+19]
 [2.36629301e+20]
 [4.28676702e+20]
 [1.87363453e+20]
 [1.24470315e+21]
 [1.00611690e+22]
 [1.00611690e+22]
 [5.20249610e+23]
 [5.20249610e+23]
 [1.12721835e+25]
 [1.12721835e+25]
 [9.40546977e+25]
 [3.29326084e+27]
 [3.00531319e+24]
 [6.61234672e+22]
 [2.86008692e+19]
 [1.24470315e+21]
 [6.61234672e+22]
 [1.00611690e+22]
 [5.20249610e+23]
 [6.04887980e+26]
 [1.35549151e+21]
 [6.04887980e+26]
 [7.97701715e+18]
 [6.72621030e+25]
 [7.97701715e+18]
 [4.28676702e+20]
 [4.98295023e+25]
 [6.72621030e+25]]


In [406]:
Magnetars = [
    "CXOU J010043.1-721134", "4U 0142+61", "SGR 0418+5729", "SGR 0501+4516", "SGR 0526-66",
    "1E 1048.1-5937", "1E 1547.0-5408", "PSR J1622-4950", "SGR 1627-41", "CXOU J164710.2-455216",
    "1RXS J170849.0-400910", "CXOU J171405.7-381031", "SGR J1745-2900", "SGR 1806-20",
    "XTE J1810-197", "Swift J1818.0-1607", "Swift J1822.3-1606", "SGR 1833-0832",
    "Swift J1834.9-0846", "1E 1841-045", "3XMM J185246.6+003317", "SGR 1900+14",
    "SGR 1935+2154", "1E 2259+586", "SGR 0755-2933", "SGR 1801-23", "SGR 1808-20",
    "AX J1818.8-1559", "AX J1845.0-0258", "SGR 2013+34", "PSR J1846-0258",
    "GRB 231115A", "GRB 200415A", "GRB 051103", "GRB 070201", "GRB 070222", "GRB 180128A"
]


In [407]:
Mag_exp = []
for i in range(37):
    a = f"{Magnetars[i]:<40} --> {total_exp[i]}"
    Mag_exp.append(a)

for entry in Mag_exp:
    print(entry)



CXOU J010043.1-721134                    --> [7.97701715e+18]
4U 0142+61                               --> [9.62478651e+18]
SGR 0418+5729                            --> [2.86008692e+19]
SGR 0501+4516                            --> [2.36629301e+20]
SGR 0526-66                              --> [9.62478651e+18]
1E 1048.1-5937                           --> [2.86008692e+19]
1E 1547.0-5408                           --> [7.18981769e+20]
PSR J1622-4950                           --> [9.25130054e+19]
SGR 1627-41                              --> [5.52104279e+19]
CXOU J164710.2-455216                    --> [2.36629301e+20]
1RXS J170849.0-400910                    --> [4.28676702e+20]
CXOU J171405.7-381031                    --> [1.87363453e+20]
SGR J1745-2900                           --> [1.24470315e+21]
SGR 1806-20                              --> [1.0061169e+22]
XTE J1810-197                            --> [1.0061169e+22]
Swift J1818.0-1607                       --> [5.2024961e+23]
Swift J1822

In [408]:
import numpy as np

max_index = np.argmax(total_exp)
print(f"Max exposure:\n{Magnetars[max_index]:<40} --> {total_exp[max_index]}")


Max exposure:
3XMM J185246.6+003317                    --> [3.29326084e+27]


In [409]:
flux_limit=np.array([34.8,26,21,16.5,23.5,12.1,25.4,28.3,14.6,28.6,30,21.2,23.8,15.2,17.2,21.1,0.2,20.9,13.2,32.2
                  ,4.1,44.3,43.5,24.8,43,31.3,12.7,19,26.6,23.1,34,14.4,9.8,16.1,16.2,8.5,21.5])
len(flux_limit)

37

In [410]:
total_exp = total_exp.flatten()  # or total_exp = total_exp.reshape(-1)
print(total_exp)
len(total_exp)

[7.97701715e+18 9.62478651e+18 2.86008692e+19 2.36629301e+20
 9.62478651e+18 2.86008692e+19 7.18981769e+20 9.25130054e+19
 5.52104279e+19 2.36629301e+20 4.28676702e+20 1.87363453e+20
 1.24470315e+21 1.00611690e+22 1.00611690e+22 5.20249610e+23
 5.20249610e+23 1.12721835e+25 1.12721835e+25 9.40546977e+25
 3.29326084e+27 3.00531319e+24 6.61234672e+22 2.86008692e+19
 1.24470315e+21 6.61234672e+22 1.00611690e+22 5.20249610e+23
 6.04887980e+26 1.35549151e+21 6.04887980e+26 7.97701715e+18
 6.72621030e+25 7.97701715e+18 4.28676702e+20 4.98295023e+25
 6.72621030e+25]


37

In [411]:
z=flux_limit/total_exp
print(z)

[4.36253293e-18 2.70135862e-18 7.34243420e-19 6.97293190e-20
 2.44161260e-18 4.23064066e-19 3.53277386e-20 3.05902936e-19
 2.64442798e-19 1.20864153e-19 6.99828095e-20 1.13149068e-19
 1.91210249e-20 1.51075885e-21 1.70954290e-21 4.05574547e-23
 3.84430851e-25 1.85412170e-24 1.17102423e-24 3.42353979e-25
 1.24496668e-27 1.47405602e-23 6.57860239e-22 8.67106515e-19
 3.45463895e-20 4.73356908e-22 1.26227877e-21 3.65209308e-23
 4.39750844e-26 1.70417887e-20 5.62087545e-26 1.80518604e-18
 1.45698686e-25 2.01829828e-18 3.77907171e-20 1.70581676e-25
 3.19645076e-25]


In [412]:
#print(min(z))
"""
for i in range(37):
    ra_mag0=ra_mag[i]
    dec_mag0=dec_mag[i]
    declcut=5
    decdiff=np.abs(ice_dec-dec_mag0)
    nuind=np.nonzero(decdiff < declcut)
    N = len(nuind[0])  
    print(N)
"""  

'\nfor i in range(37):\n    ra_mag0=ra_mag[i]\n    dec_mag0=dec_mag[i]\n    declcut=5\n    decdiff=np.abs(ice_dec-dec_mag0)\n    nuind=np.nonzero(decdiff < declcut)\n    N = len(nuind[0])  \n    print(N)\n'

In [425]:
declcut = 5 
band = 5   
w_model=1
delta_i = ice_dec[i]
N=len(ice_ra)
def angular_separation(ra1, dec1, ra2, dec2):
    delta_ra = ra1 - ra2
    return np.arccos(np.sin(dec1) * np.sin(dec2) + np.cos(dec1) * np.cos(dec2) * np.cos(delta_ra))

def bg(dec_mag0,N, twopi = True):
        decdiff=np.abs(ice_dec-dec_mag0)
        nuind=np.nonzero(decdiff < declcut)
        N_i = np.sum(decdiff < declcut)
        if twopi == True:
            s_ang = (np.sin(np.radians(dec_mag0 + band)) - np.sin(np.radians(dec_mag0 - band)))*(2 * np.pi)
            return (N_i/N)*(1/s_ang)
        else:
            s_ang = (np.sin(np.deg2rad(dec_mag0 + band)) - np.sin(np.deg2rad(dec_mag0- band)))
            return N_i/s_ang*N
#for i in range(0,37):
   # dec_mag0=dec_mag[i]
   # B_i= bg(dec_mag0,N,twopi = True)
   # print(B_i)
#print(N)

In [426]:
F=phiE2
a=10**-7/(10**5)**2
b=10**-11/(10**5)**2
phi0= np.logspace(-21, -18, 40)
dF_by_dE=phi0*F
area1_f=Eff_1*dF_by_dE
area2_f=Eff_2*dF_by_dE
area3_f=Eff_3*dF_by_dE
area4_f=Eff_4*dF_by_dE
area5_f=Eff_5*dF_by_dE
eff_int1=np.trapz(area1_f,x=E)
eff_int2=np.trapz(area2_f,x=E)
eff_int3=np.trapz(area3_f,x=E)
eff_int4=np.trapz(area4_f,x=E)
eff_int5=np.trapz(area5_f,x=E)
#print(eff_int1)
#print(area1_f)
#print(Eff_1)
#print(dF_by_dE)
#type(eff_int1)
x_axis=E**2*dF_by_dE
#print(x_axisi[0])
#print(phi0.shape)
#print(F)
#print(phiE_2)

In [427]:
print(F)

[[4.60256574e-08 1.47570653e-07 4.73151259e-07 1.51705037e-06
  4.86407206e-06 1.55955250e-05 5.00034535e-05 1.60324539e-04
  5.14043652e-04 1.64816239e-03 5.28445252e-03 1.69433780e-02
  5.43250331e-02 1.74180687e-01 5.58470195e-01 1.79060585e+00
  5.74116462e+00 1.84077200e+01 5.90201080e+01 1.89234362e+02
  6.06736330e+02 1.94536008e+03 6.23734835e+03 1.99986187e+04
  6.41209577e+04 2.05589060e+05 6.59173895e+05 2.11348904e+06
  6.77641508e+06 2.17270118e+07 6.96626514e+07 2.23357222e+08
  7.16143410e+08 2.29614865e+09 7.36207097e+09 2.36047823e+10
  7.56832895e+10 2.42661010e+11 7.78036551e+11 2.49459473e+12]]


In [428]:
expo_f1=(eff_int1)*datatimesum1
expo_f2=(eff_int1)*datatimesum2
expo_f3=(eff_int1)*datatimesum3
expo_f4=(eff_int1)*datatimesum4
expo_f5=eff_int5*datatimesum5
expo_f6=eff_int5*datatimesum6
expo_f7=eff_int5*datatimesum7
expo_f8=eff_int5*datatimesum8
expo_f9=eff_int5*datatimesum9
expo_f10=eff_int5*datatimesum10
#print(expo_f1)
ns=(np.sum(expo_f1+expo_f2+expo_f3+expo_f4+expo_f5+expo_f6+expo_f7+expo_f8+expo_f9+expo_f10))
print(ns)
#print(expo_f1)

9.659208039741045e+26


In [429]:



def sig(ra_mag0,dec_mag0,ra_mag1,dec_mag1,ice_ra1,ice_dec1 ,iceang,declcut):
        decdiff=np.abs(ice_dec-dec_mag0)
        nuind=np.nonzero(decdiff < declcut)
        sg=np.radians(iceang[nuind])**2
        Ang_sep1=(np.arccos((np.sin(ice_dec1[nuind])*np.sin(dec_mag1)+np.cos(ice_dec1[nuind])*np.cos(dec_mag1)*np.cos(ice_ra1[nuind]-ra_mag1))))**2
        return ((np.exp(-1*Ang_sep1/(2*sg)))/(2*np.pi*sg))
    
def sig_i(w_accj,ra_mag0,dec_mag0,ra_mag1,dec_mag1,ice_ra1,ice_dec1 ,iceang,declcut):
    return np.sum(w_accj*sig(ra_mag0,dec_mag0,ra_mag1,dec_mag1,ice_ra1,ice_dec1 ,iceang,declcut))/np.sum(w_accj*w_model)


def P(N,ns,S_i,B_i):
    return (ns/N)*S_i+(1-(ns/N))*B_i
    
def TS(N,ns,S_i,B_i):
        return 2*np.sum(np.log((P(N,ns,S_i,B_i)/B_i)))
    

ice_ra1 = np.radians(ice_ra)
ice_dec1 = np.radians(ice_dec)

Ts_values = []
sqrt_TS = []
#Background = []

for i in range(0,37):
    ra_mag0=ra_mag[i]
    dec_mag0=dec_mag[i]
    ra_mag1=np.radians(ra_mag0)
    dec_mag1=np.radians(dec_mag0)
    w_accj=total_exp[i]
    B_i=bg(dec_mag0,N, twopi = True)
    TS_i=TS(N,ns,S_i,B_i)
    S_i=sig_i(w_accj,ra_mag0,dec_mag0,ra_mag1,dec_mag1,ice_ra1,ice_dec1 ,iceang,declcut)
    Ts_values.append(TS_i)
    sqrt_TS.append(np.sqrt(TS_i))
    #Background.append(B)

print(Ts_values)
    #print(x_axisi)
    #plt.plot(x_axisi[0],TS_i)
  #  plt.show()
    

[124.78970967338074, 124.31151515973374, 124.16302781340222, 124.15835579387362, 124.39899707492408, 124.28573165091511, 123.92527074221083, 124.24172479998721, 124.27533430136124, 124.08953545756931, 124.24828340482748, 124.28474527230583, 123.99213351047521, 124.07412284781137, 124.07189617432586, 124.0045885944399, 124.18931887266244, 124.23343714408335, 124.21286709058428, 123.88946674345162, 124.62068092428724, 124.51005260427101, 124.98360999553347, 125.33857762513229, 123.75894861756576, 124.41599038219788, 124.41002182125426, 123.86588141546952, 123.72010123867508, 125.22898446587186, 123.26475023882274, 125.94024593762731, 123.78059610060322, 124.35983110204432, 123.69543295695254, 124.33327369754376, 123.99659851376495]


In [432]:

#plt.plot(x_axis, Ts_values)

print(x_axis)

[[7.29457510e-35 7.01331066e-34 6.74289123e-33 6.48289863e-32
  6.23293084e-31 5.99260131e-30 5.76153841e-29 5.53938484e-28
  5.32579708e-27 5.12044484e-26 4.92301058e-25 4.73318900e-24
  4.55068656e-23 4.37522105e-22 4.20652115e-21 4.04432599e-20
  3.88838475e-19 3.73845629e-18 3.59430879e-17 3.45571932e-16
  3.32247360e-15 3.19436556e-14 3.07119712e-13 2.95277782e-12
  2.83892452e-11 2.72946119e-10 2.62421854e-09 2.52303385e-08
  2.42575064e-07 2.33221847e-06 2.24229272e-05 2.15583434e-04
  2.07270961e-03 1.99279001e-02 1.91595196e-01 1.84207663e+00
  1.77104978e+01 1.70276159e+02 1.63710646e+03 1.57398286e+04]]
